### ISSUE TITLE
Correct format for plotting multiple bams

### ISSUE THREAD

**Issue by 690645258** [rrazaghi/modbamtools#18]
Hi,

I'm trying to plot multiple bams, but the formatting of how to provide sample names/bams is unclear to me and not mentioned in the tutorial.

I've tried 

modbamtools plot --batch $newoutdir/init.bed \
    --gtf $gtf \
    --out $newoutdir \
    --prefix comparison \
    --track-titles Genes\
    -s Treated,Control
    $treated \
    $control

and 

modbamtools plot --batch $newoutdir/init.bed \
    --gtf $gtf \
    --out $newoutdir \
    --prefix comparison \
    --track-titles Genes\
    -s Treated $treated \
    -s Control $control

and

modbamtools plot --batch $newoutdir/init.bed \
    --gtf $gtf \
    --out $newoutdir \
    --prefix comparison \
    --track-titles Genes\
    -s Treated $treated Control $control
  
all without any success.

**Comment by rrazaghi** [comment]
First one should work. What’s the output and what version are you using?

**Comment by 690645258** [comment]
I'm using version 0.4.8,

Output for the first gives me:


```
processing chr21        10401476        10409738

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/workhorse/bin/modbamtools", line 8, in <module>
    sys.exit(cli())
  File "/home/user/miniconda3/envs/workhorse/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/miniconda3/envs/workhorse/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/miniconda3/envs/workhorse/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/miniconda3/envs/workhorse/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/miniconda3/envs/workhorse/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/miniconda3/envs/workhorse/lib/python3.9/site-packages/modbamtools/cli.py", line 269, in plot
    plot = Plotter(
  File "/home/user/miniconda3/envs/workhorse/lib/python3.9/site-packages/modbamtools/modbamviz.py", line 100, in __init__
    assert self.num_tracks == len(self.titles)
AssertionError
```

**Comment by rrazaghi** [comment]
Hi,
Sorry for the delay, I was out of office!

I can't reproduce this on my end. Could you provide the script and small reproducible modbam for this?
